README.md, _config.yml, index.md, pages/bodystorming.md, pages/content-audit.md, pages/design-studio.md, pages/fundamentals.md, pages/journey-mapping.md, pages/site-mapping.md
This reflects changes made Friday for print space. (There were other
changes for print that materially affected the content. Those referred
people back to the digital version. So it would be pretty
counterproductive to fold those in.)
@jenniferthibault
=> Reconciling with print edits

_includes/footer.html
@vz3: Jen, Jeannine and I liked the idea of putting our solicitation for feedback (via Github) in the footer. This PR does that. Feel free to close, modify, reply or do whatever's best! 
@jeanninehunter, @jenniferthibault: Feel feel to take a look and propose changes, too.
=> Add feedback solicitation, remove "edit this page"

index.md
Minor copy edit to emphasize the function, not just the aesthetic (pretty sure that’s your language anyway, Jen)
@jenniferthibault 
Once this is pulled in I think the branch looks good and I’ll pull it to staging!
=> Small change

pages/kj-method.md, pages/usability-testing.md
Updates kj-method & usability-testing with more accurate (and generous!) count of how many members of the public can be included without triggering PRA.
Addresses #37
=> Small session pra language

pages/incentives.md, pages/recruiting.md
=> Incentives, recruiting clarifications

pages/incentives.md
- acknowledging that agency policies on incentives can differ
- noting that outside expertise in recruiting can be helpful
@colinpmacarthur
Asking for Colin since I want to merge it into his branch, which we’ll then merge into staging. This is probably overkill for a single change, but it makes me feel more comfortable that we’re not creating conflicts for minor things.
=> Governmenting it up a bit

pages/incentives.md
Adds this sentence to the incentives card: 
> In government, contractors or recruiting tools (like <a href="http://ethn.io">ethn.io</a>) can often pay incentives.
I'm trying to give actionable advice, but address issues remaining in #36 without waiting for further advice (which could take a while).
=> Clarifying incentives card for govt. readers

.travis.yml
This PR changes the encrypted password in travis.yml to meet new 18F Cloud Foundry password requirements.
=> Fixing password in .travis.yml

_includes/footer.html
Thanks to @laurenancona for pointing this out in #63 !
=> Corrects the footer link to the 18F pages repository

pages/design-studio.md, pages/journey-mapping.md, pages/mental-modeling.md, pages/metrics-definition.md
Nothing that affects meaning too much, except on Mental Modeling, which I updated for consistency’s sake.
=> A couple more style changes to additional resources

Gemfile.lock
Resolves #83 where the accordion element wasn’t working in the sub-nav pages. 
I **think** I did this right?
@mbland (if you have time?) If not, let us know. Thank you!
Thanks @noahmanger for pointing this out!
=> Updates gemfile

.about.yml
- added beta print run as project update
- listed team members as 18F staffers who have attended meetings on the topic in the last 60 days or contributed code in the last 90 days. i figure this list can helpfully answer any questions about current state of things.
@carodew 
@colinpmacarthur 
* Feel free to suggest anything that’s missing. These were the big ones that occurred to me. This is ultimately to populate the dashboard and project list.
* Once this is pulled in, I’ll issue another PR to bring the branch into staging.
=> Brought about copy up to date

pages/kj-method.md
This reflects the changes necessary to fit the new PRA edits onto the printed card. Google doc of edits [here](https://docs.google.com/document/d/1WUBYMxos7JFFdyO93mZAAilo8LRuf1ZrakTUDozuMIc/edit).
=> Updating KJ copy

_pages/make/prototyping.md
If this works on staging, will correct all other URLs.
=> test new URL format on prototyping.md

_pages/decide/personas.md, _pages/fundamentals/recruiting.md, _pages/validate/multivariate-testing.md
Found a few URLs I missed in #108 , adding those
=> fixed three few more URLs

_pages/discover/kj-method.md
Put "Example from 18F" above "additional resources"
=> Reversed headings to be consistent w/ other pages

_pages/decide/mental-modeling.md
=> Remove book purchase link

_pages/discover/design-studio.md
Reword bullet to be clearer and shorter.
=> Design studio edits

_pages/decide/mental-modeling.md
Made style more consistent. Some editing for clarity.
=> Edits to mental modeling

_pages/discover/stakeholder-and-user-interviews.md
Reworked the instructions and removed some of the examples. Didn't have a good place to include a nod to existing body of interview guidance. This feels like a step in the right direction but might need another pass that directs people to the many larger issues of stakeholder interviews.
=> Rework stakeholder interview how to section

index.md
Deleted "why methods cards" section. Added "what's new" section with recent updates.
=> Homepage content tweaks - additions/deletions

_pages/discover/cognitive-walkthrough.md
I revised the text to call out the fact that this method can be done without real users (which is one of the benefits), but that it is no substitute for user evaluation.
=> Cog walkthrough eds.

_pages/decide/journey-mapping.md
I think with the edits to the task flow card, these two methods are now pretty distinct. Just made a few tweaks here for clarity.
=> A few minor eds

_pages/decide/user-scenarios.md
Updated the What it is, Reasons to do it, and How to do it sections on the page
=> Updated content on User Scenarios method card

_pages/decide/user-scenarios.md
Updated personas link to add a trailing slash
=> Updated personas link

_pages/fundamentals/privacy.md
=> Copy edits to Privacy

_pages/fundamentals/incentives.md
=> Copy edits to incentives

_pages/validate/visual-preference-testing.md
Some plain language edits. I think the instructions could still be clearer, but this is closer and is the extent of my knowledge about this activity.
=> Visual preference testing edits

_pages/decide/task-flow-analysis.md
Here is a first take. Trying to thread the needle by not referring to use cases (although, wondering if that use case ever come up as a card folks want? It is a bit engineery, and I know some designers are biased against the term, but as I see it, it is really the highest tier in the three part hierarchy of use case, user scenario, and task)...
=> Task flow analysis edits

_methods/card-sorting.md
Copied over clarity edits from old site.
=> NEW-CardSort-clarity eds

_methods/comparative-analysis.md
Copied over plain language edits from old site.
=> NEW-compAnalysis-clarityEds

_methods/journey-mapping.md
Copied over plain language eds from old site.
=> NEW-JourneyMap-clarityEds

_methods/task-flow-analysis.md
Copied over clarity eds from old site.
=> NEW-TaskAnalysis-clarityEds

_methods/visual-preference-testing.md
Copied clarity edits over from old site.
=> NEW-VisPrefTest_clarityEds

_methods/incentives.md
Copied over clarity eds from old site.
=> NEW-incentives-clarityEds

_methods/privacy.md
Copied over minor clarity eds from old site.
=> NEW-Privacy-clarityEds

_methods/metrics-definition.md
- Converted front matter to use markdown
=> Updates to metrics definition method

_methods/wireframing.md
Copied over clarity edits from old site.
=> NEW-wireframing-ClarityEds

_methods/design-pattern-library.md
Copied over clarity eds from the old site.
=> NEW-PatternLib-clarityEds

_methods/user-scenarios.md
Copy over clarity edits from old site.
=> NEW-UserScenario-clarityEds

_includes/header.html, _includes/method-print-header.html
Adding tracking on print link in top nav, print links from card and
category pages and viewing method category links.
=> Adding Google Analytics tracking

_methods/bodystorming.md
=> + permalink bodystorming

_methods/affinity-diagramming.md
=> +permalink affinity diagram

_methods/card-sorting.md, _methods/comparative-analysis.md, _methods/content-audit.md, _methods/contextual-inquiry.md, _methods/design-pattern-library.md, _methods/design-principles.md, _methods/dot-voting.md, _methods/heuristic-analysis.md, _methods/incentives.md, _methods/journey-mapping.md, _methods/kj-method.md, _methods/mental-modelling.md, _methods/metrics-definition.md, _methods/multivariate-testing.md, _methods/personas.md, _methods/privacy.md, _methods/prototyping.md, _methods/recruiting.md, _methods/site-mapping.md, _methods/stakeholder-and-user-interviews.md, _methods/storyboarding.md, _methods/style-tiles.md, _methods/task-flow-analysis.md, _methods/usability-testing.md, _methods/user-scenarios.md, _methods/visual-preference-testing.md, _methods/wireframing.md
Added all remaining permalinks.  I created separate PRs for a few (Melissa 1 and Melissa 2) before I got into the flow of adding them all in the same branch.
=> +permalinks

_methods/affinity-diagramming.md, _methods/bodystorming.md, _methods/contextual-inquiry.md, _methods/design-principles.md, _methods/design-studio.md, _methods/dot-voting.md, _methods/heuristic-analysis.md, _methods/journey-mapping.md, _methods/metrics-definition.md, _methods/multivariate-testing.md, _methods/personas.md, _methods/privacy.md, _methods/prototyping.md, _methods/site-mapping.md, _methods/stakeholder-and-user-interviews.md, _methods/storyboarding.md, _methods/usability-testing.md, _methods/user-scenarios.md, _methods/visual-preference-testing.md, _methods/wireframing.md
There were quite a few broken links that needed to be fixed in the descriptions of the methods.
=> Fix broken links

_methods/bodystorming.md, _methods/metrics-definition.md
Content issue fixes for “Bodystorming” and “Metrics Definition” methods.
=> Fixing some minor content issues

_includes/footer.html, assets/js/site.js
This addresses https://github.com/18F/methods/issues/233
=> Collapse menu when selection is made

README.md
README now points to 18F style guide
=> README now points to 18F style guide

_pages/about.md
Preview - https://federalist-proxy.app.cloud.gov/preview/18f/methods/release-notes-1/about/
=> Pull in latest release notes

_config.yml
[Preview](https://federalist-proxy.app.cloud.gov/preview/18f/methods/fix-baseurl/)
=> updating site.baseurl to run locally

.gitignore, _includes/header.html, _sass/uswds_overrides.scss
**Solves #342 (and half of #315) ...**
**and #329 …**
=> Changed button backgrounds to white, linked header nav to individual method pages

_includes/head.html, _includes/method.html
Added image for Twitter cards and formatted image tag for Schema.org
meta info.
This closes #61
=> Adding updates for meta info

_sass/method.scss, _sass/print.scss
**Preview**
https://federalist-proxy.app.cloud.gov/preview/18f/methods/sw-clickable-title/
closes #330
=> Adding underline to method titles

_includes/header.html, _includes/print.html, _pages/interview-checklist.md, _sass/print.scss, deck.html, pages/deck.html, pages/print.html
Adding a deck page, this probably needs a bit of love but it's here 🌺 
👀 preview https://federalist-proxy.app.cloud.gov/preview/18f/methods/sw-deck-page/print/
👀 preview https://federalist-proxy.app.cloud.gov/preview/18f/methods/sw-deck-page/interview-checklist/
=> Adding deck as a page

README.md
H1 was missing and otherwise started at H3. Maybe someone has a better structure idea
=> chore: Update heading structure

PRODUCT_OWNER.md, README.md
=> Add product owner role description to repo

README.md
=> Revert "Updated README with mission & vision"

_methods/content-audit.md
Found it to be a good walkthrough.
=> link to the usability.gov Content Inventory page

_methods/user-scenarios.md
Preview here: 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/methods/updateuserscenario/decide/user-scenarios/
=> Update User Scenario

_methods/journey-mapping.md
Added an example I found that the CX COE did with USDA: https://coe.gsa.gov/coe/farm-loans/index.html#journeymap
=> Add example from USDA and CX COE

_data/categories.yml
REMINDERS (Delete this before submitting your pull request)
Before submitting your pull request, please preview your changes at  https://federalist-proxy.app.cloud.gov/preview/18f/methods/[BRANCHNAME] (where [BRANCHNAME] is the name of your branch) This is the main URL we will reference as we review and comment on your pull request.
Please submit pull requests against the `staging` branch.
Finally, please note that all pull requests must receive at least one review in addition to whomever merges the request. When you believe your code is ready to merge, please tag at least one member of the current Methods team (see README.md).
=> Add 5 Whys to homepage

_data/categories.yml, _methods/lean-coffee.md
[Preview here](https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/Lean-coffee/discover/lean-coffee/)
=> Add new method: Lean coffee

_data/categories.yml, _methods/affinity-mapping.md
[Preview](https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/affinity-mapping/decide/affinity-mapping/)
Resolves Issue #400
=> Affinity mapping

_methods/journey-mapping.md
replace CoE journey map example link with 3-part series on what, why, and how of journey mapping from CoE which includes links to multiple examples #446
Preview available at: https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/446-change-journey-mapping-link/decide/journey-mapping/
=> Swap out Journey Mapping resource link

_sass/touchpoints_overrides.scss
=> flatten the bottom left and right radius

_config.yml
build was failing due to incorrect yaml syntax
https://federalistapp.18f.gov/sites/466/builds/151967/logs
=> Fix dap values in config

_methods/five-whys.md
> You may __can__ "why"
to 
> You may __ask__ "why"
=> Typo in content

_sass/participant-agreement.scss
Removes extra `padding-right` from desktop view
=> Updates to participant-agreement.md

_includes/header.html
To ensure this site is compliant, added alt text to 18F logo in header.
=> Added alt text to 18F logo in the header

_includes/category-setup.html
=> Fix comment bug on about page.

_data/categories.yml
Changed "incentives" to "compensation" in index to match new, OGC approved language.
=> Changed "incentives" to "compensation"

PULL_REQUEST_TEMPLATE.md
REMINDERS (Delete this before submitting your pull request)
Before submitting your pull request, please preview your changes at  https://federalist-proxy.app.cloud.gov/preview/18f/methods/[BRANCHNAME] (where [BRANCHNAME] is the name of your branch) This is the main URL we will reference as we review and comment on your pull request.
Please submit pull requests against the `main` branch.
Finally, please note that all pull requests must receive at least one review in addition to whomever merges the request. When you believe your code is ready to merge, please add the `guide-admin` team as reviewers.
=> Updated PR template w/ new pages preview link

Dockerfile, README.md, docker-compose.yml
In order to be consistent with how we build 18F websites, and in order to avoid environment-specific errors, I'm containerizing this site by adding a Dockerfile and some basic Docker configs.
=> Dockerize the local build

.github/sync.yml, .github/workflows/sync_templates.yml
This PR automatically syncs changes to issue and pull request templates with other guides repositories (currently just the methods repo). It should be easily extensible to other repos by adding them to the list in the new `.github/sync.yml` config file.
Addresses #589
=> Sync issue and PR templates

.github/sync.yml, .github/workflows/sync-labels.yml, .github/workflows/sync_templates.yml
- if a synchronized file is deleted from one repo, also delete it from other repos
- when a label is added, modified, or deleted from this repo, immediately synchronize it to the ux-guide repo
- I'll need to make this update in the ux-guide repo as well
=> Update repo synchronization automations

.github/sync.yml, .github/workflows/sync_templates.yml
Unfortunately it currently seems broken. My working hypothesis is that it's trying to sync empty changes and that's causing problems. I don't *really* think that's the problem, but it's something I want to eliminate.
So in this PR, I revert back to only trigger the sync when syncable files change and I modify synced files. That way if the problem is syncing an empty change set, this PR will force a non-empty sync and we'll see the problem go away. If the problem persists, then it's not (just?) a problem of empty change sets.
=> Experimenting with repo syncing

CONTRIBUTING.md
REMINDERS (Delete this before submitting your pull request)
Before submitting your pull request, please preview your changes at  https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/[BRANCHNAME] (where [BRANCHNAME] is the name of your branch) This is the main URL we will reference as we review and comment on your pull request.
Please submit pull requests against the `main` branch.
Finally, please note that all pull requests must receive at least one review in addition to whomever merges the request. When you believe your code is ready to merge, please add the `guide-admin` team as reviewers.
=> Added PR instructions to CONTRIBUTING

.github/workflows/sync_wiki.yml
This pull request adds an automation that synchronizes changes made to the Methods wiki into the UX-guide wiki. There will be a companion PR on the UX-guide repo after this one is merged.
=> Sync wiki pages to UX-guide

_includes/footer.html, _layouts/card.html, _sass/category.scss, _sass/footer.scss, _sass/method.scss, assets/application.js, index.html
Updated application.js, styling, and added the SVG to the footer. This update is so the heading links will be accessible to screenreaders, instead of reading `#`.
=> Change header links to be accessible

README.md
Update of contributors and product owner; a few other clarity edits.
=> update contributors, a few other small edits

Gemfile.lock
This PR undoes changes to the Gemfile applied in branch dependabot/bundler/activesupport-7.0.7.2
it is intended to address broken assets in the live deployment of https://methods.18f.gov/
=> Jskinne3 undo prior
