18F/methods

index.md, pages/affinity-diagramming.md, pages/bodystorming.md, pages/card-sorting.md, pages/cognitive-walkthrough.md, pages/comparative-analysis.md, pages/contextual-inquiry.md, pages/design-studio.md, pages/journey-mapping.md, pages/prototyping.md, pages/stakeholder-and-user-interviews.md, pages/usability-testing.md
mostly this was adding links to other method pages where appropriate. a
couple other minor things:
- consistent punctuation in index page headers
- changed an incorrect reference in the gov research section of
cognitive-walkthrough
- inserted a missing comma
- removed an extra in-line space
- changed a straight apostrophe to curled
@jenniferthibault 
In two places I linked references to a competing product to the comparative analysis file. In context, the references are to understanding opportunities and patterns based on observing user behavior. Comparative analysis gives you a way of identifying which behaviors you’d be testing for. But I’m not sure if people will be confused by going to something with different words in the title. /shrug
=> helping users find other methods (etc.)

index.md, pages/decide.md
- spelling for comparitive/comparative
- fixed directory reference (I think) for foundations
=> Fixing parent page links

pages/card-sorting.md, pages/cognitive-walkthrough.md, pages/design-studio.md, pages/heuristic-analysis.md, pages/mental-modeling.md, pages/metrics-definition.md, pages/recruiting.md, pages/stakeholder-and-user-interviews.md
- Card Sorting: Made two sub-categories h3 instead of h2
- Cognitive walkthrough: Made Additional resources h2, missing ##
- Design studio: changed hyphens to en-dashes
- Heuristic analysis: Added “To” to beginning of Reasons to match
format of others
- Mental modeling, Metrics definition, Design studio: Made “I” in
“Implications” lowercase
- Stakeholder and user interviews: changed time required to Medium to match how we were including prep time in these recommendations
- Recruiting: Trying to correct markdown format, adding space between
bulleted list so that bullets render
@jameshupp 
- Thank you James for this excellent commit format that I'm copying now.
- Probably want to check that the formatting fixes for Recruiting and Cognitive walkthrough actually worked. I'm not a markdown pro …
=> Copy edits found while putting content into the print template

.travis.yml, Staticfile, _config-production.yml, manifest.yml
When pushed to the "18f-pages" branch, these files should:
1. Build the Jekyll site (using both _config.yml and _config-production.yml, so the built version has the right base URL for deployment to methods.18f.gov). 
2. Push the built version to the "methods" CloudFoundry space, which is viewable at methods.18f.gov
I am a bit outside my comfort zone here, so I'd really appreciate your review, @vz3 and @ozzyjohnson. Thanks so much for all your help!
=> Enabling Travis CI, CloundFoundry on production

.travis.yml, _includes/footer.html
When pushed to the "master" branch, these files should:
1. Build the Jekyll site (using both _config.yml and _config-production.yml, so the built version has the right base URL for deployment to methods.18f.gov). 
2. Push the built version to the "methods" CloudFoundry space, which is viewable at methods.18f.gov
=> Enabling Travis CI and Cloud Foundry

pages/card-sorting.md, pages/cognitive-walkthrough.md, pages/decide.md, pages/mental-modeling.md
Updated the congitive walkthrough method. The substance of it was fine, but the language needed editing to bring it in line with where the other methods are.
Additional small things:
* Fixed an alphabetical ordering issue on Decide.
* Made two small edits to other cards, one for number and one to remove an extra word.
* I re-checked all the methods after making the cognitive walkthrough update, so we shouldn’t need anything this significant again soon. The other methods all reflected edits we’d made offline. I think I just overlooked just the how-to section of that card.
* This PR addresses #27.
=> Cognitive walkthrough update

pages/protosketching.md
Currently the online version links to: "https://methods.18f.gov/protosketching/%5Bhttps://18f.gsa.gov/2015/01/06/protosketch/%5D"
Broken link on this page: https://methods.18f.gov/protosketching/
=> Fix broken link in Protosketching

pages/informed-consent.md, pages/recruiting.md
Fixing broken consent form links on both the "recruiting" and "informed consent" card.
=> Fixing consent form links

README.md
Not sure why /methods/ worked for me before, but I just tested it and it doesn’t anymore. Ending on the port number does, though.
@colinpmacarthur 
@jenniferthibault 
(Just because you two were active  on this project earlier; it’s really anyone who has 30 seconds to serve the site locally and see how it works.)
=> Fixing local instance URL

Gemfile.lock, _config_18f_pages.yml, go
Necessary since this repo contains many of its own style settings. Closes #54.
To try this out locally, run `./go serve --config _config.yml,_config_18f_pages.yml`.
Also updates the `./go` script so you can pass arguments to `./go build` and `./go serve`, and bumps the `guides_style_18f` theme to the latest, v0.1.4.
cc: @jenniferthibault @vz3 @jameshupp
=> Add _config_18f_pages.yml to set asset_root

pages/affinity-diagramming.md, pages/bodystorming.md, pages/cognitive-walkthrough.md, pages/content-audit.md, pages/design-principles.md, pages/design-studio.md, pages/kj-method.md, pages/metrics-definition.md, pages/protosketching.md, pages/prototyping.md, pages/usability-testing.md
- Removed hyphens when there was only one resource
- Removed duplicate periods from affinity diagramming, content audit,
and metrics definition
@jenniferthibault 
@RyanSibley 
If Ryan can confirm that the second bullet brings it into line with the original formatting, Jen you should be able to merge this into your branch and then we can pull the whole thing into staging.
=> Style fixes to the additional resources update

pages/affinity-diagramming.md, pages/bodystorming.md, pages/cognitive-walkthrough.md, pages/content-audit.md, pages/design-pattern-library.md, pages/design-principles.md, pages/design-studio.md, pages/feature-dot-voting.md, pages/heuristic-analysis.md, pages/informed-consent.md, pages/journey-mapping.md, pages/kj-method.md, pages/mental-modeling.md, pages/metrics-definition.md, pages/multivariate-testing.md, pages/personas.md, pages/protosketching.md, pages/prototyping.md, pages/recruiting.md, pages/storyboarding.md, pages/style-tiles.md, pages/task-flow-analysis.md, pages/usability-testing.md, pages/user-scenarios.md, pages/visual-preference-testing.md
- Formatted naked hyperlinks
- Structured resources listings in a more friendly way, so that users would know what they are clicking to.
- Determined we would use only outside, non-18F authored content as resources in the "Additional resources” section. 18F blog posts are ok if we can’t find anything else, but otherwise we should try to steer clear of things written by 18F folks or on sites owned/managed by 18F folks. This resulted in removing a few resources from pages already containing other links.
Thanks to @RyanSibley for the content strategy & editorial lift!
@jameshupp
=> Formatting hyperlinks in "Additional resources" section

_config.yml
Resolves #82
*Notes:* Validate is already ordered alphabetically in its category, and Fundamentals
doesn’t have a sub-category, so they didn’t change.
*Review:* @jameshupp
=> Re-orders nav items in Discover/Decide/Make

.travis.yml
`sudo` may not be necessary and removing it could speed up travis builds.
=> Remove sudo: true from travis

pages/bodystorming.md, pages/card-sorting.md, pages/cognitive-walkthrough.md, pages/contextual-inquiry.md, pages/design-principles.md, pages/journey-mapping.md, pages/protosketching.md, pages/prototyping.md, pages/stakeholder-and-user-interviews.md, pages/usability-testing.md, pages/visual-preference-testing.md
Changed 5 CFR 1320.5(h)3 and 5 CFR 1320.5(h)7 to 5 CFR 1320.3(h)3 and 5 CFR 1320.3(h)7 (changed .5 to .3 in two places)
=> correct typo in PRA references

_pages/decide/affinity-diagramming.md, _pages/decide/design-principles.md, _pages/decide/journey-mapping.md, _pages/decide/personas.md, _pages/decide/site-mapping.md, _pages/decide/storyboarding.md, _pages/decide/user-scenarios.md, _pages/discover/bodystorming.md, _pages/discover/contextual-inquiry.md, _pages/discover/design-studio.md, _pages/discover/feature-dot-voting.md, _pages/discover/heuristic-analysis.md, _pages/discover/metrics-definition.md, _pages/discover/stakeholder-and-user-interviews.md, _pages/make/prototyping.md, _pages/make/wireframing.md, _pages/validate/multivariate-testing.md, _pages/validate/usability-testing.md, _pages/validate/visual-preference-testing.md
Change format for all body copy URLs (excluding index/category pages) from `[competing product](/../decide/comparative-analysis/)` format to `[competing product]({{ '/discover/whatever' | prepend: site.baseurl }})` format, so that URLs will work locally and on staging, and (fingers severely crossed) even on production!
=> fix body copy URLs with Jekyll-y prepended URLs

_includes/ethnio.html, _layouts/default.html
This pull request is to officially remove the Ethnio code from https://methods.18f.gov/. There was a [commit from the staging branch](bedab24b06a5f1b260afc60739633c9f6195792) that @jehlers and I were unsure whether or not they could be included on production yet, hence the rationale behind not merging `staging` > `master`. 
I also added one commit to remove it from the `default.html` layout file too.
Once this is merged in, please submit another pull request to merge `master` into `staging`.
=> Remove Ethnio codebase from live site.

_layouts/default.html
Removing a last reference to the Ethn.io snippet page in the includes folder. (We removed that snippet, so this reference is breaking the build.)
=> Removing Ethn.io reference from default page template

_pages/make/protosketching.md
Moved e.g. from under "additional resources heading to under "examples from 18F." Also deleted "additional resources" heading because it was no longer needed.
=> Moved 18F e.g. up under 18F e.g. heading

_pages/discover/feature-dot-voting.md
Remove "user stories" because "potential features" seems to cover pretty much the same ground here. Let me know if that's not the case. 
Change Post-it and glue dots to more plain language. 
Other small changes.
=> Plain language edits

_includes/method-print-header.html, _sass/uswds_overrides.scss, _sass/variables.scss
Adds the button styles from the 18F site: 
Documentation: https://18f.gsa.gov/styleguide/components/#buttons
Code: https://github.com/18F/18f.gsa.gov/blob/master/_sass/_components/buttons.scss
- Uses `button-secondary` following style guidance due to the page
background colors
- Adds 18F color variables
- Adds primary and secondary button styles
@line47 when adding these styles, I hit a wall when I added the `.usa-button-secondary` class, which started interfering with the previous "button" styling. Here's a screenshot of the current state:
Any pointers on what I'm doing wrong?
=> Adds 18F button styles

_includes/method.html, _methods/prototyping.md
- Updated the method file to allow for the `why` content to be Markdown
- Updated the anchor tag variable so it would populate with the method
title
=> Convert prototyping method to markdown

_includes/method.html, _methods/multivariate-testing.md, _methods/usability-testing.md, _methods/visual-preference-testing.md
Converted Multivariate testing, Usability testing and Visual preference
testing methods to use Markdown
Added the ability to use markdown in `timeRequired` as the Visual
preference testing method needs that support.
=> Converting validate methods to Markdown

_sass/uswds_overrides.scss
The text of the expanded nav button is black when you hover over it, making it hard to read. This ensures it stays white.
Before:
After:
=> Fix navigation button color on expanded hover

_methods/design-studio.md
Added permalink to design studio method
Preview: https://federalist-proxy.app.cloud.gov/preview/18f/methods/missing-permalink/
Permalink was missing the category in the URL: `/design-studio/`
Permalink is now:  `/discover/design-studio/`
=> permalink was missing

CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, README.md
Hey @ericronne @line47,
In re-orienting myself to this project, I took some time yesterday to clean up some of the "meta" files describing our GitHub repo, including our contribution guidelines (`CONTRIBUTING.md`). This pull request moves the "what to include in an issue" from `CONTRIBUTING.md` to `ISSUE_TEMPLATE.md` (which means that those instructions will now pre-populate within an issue should someone choose to create one). I've also migrated some information to `PULL_REQUEST_TEMPLATE.md` file for helpful information about that workflow.
In the `PULL_REQUEST_TEMPLATE.md` file I suggest that PRs require reviews by someone on the Methods team. To clarify who that is, I've added the current Methods team to the `README.md`. I've also updated the `README.md` file to quickly describe the …
=> Update readme, contributing, issue and PR templates PR.

_includes/header.html
**Changes**
- Adds `aria-hidden=true` to pull-down menus
**Notes** 
This bug appears to exist in the [web standards pull down menus as well](https://standards.usa.gov/components/headers/basic/). Since JavaScript is adding the aria-hidden attribute and CSS is relying on it to hide the menus, we end up with a race during page load to execute the JS fast enough to hide the menus before CSS can render. This prevents that from happening by adding the default attributes in markup. 
**Screenshots**
Closes https://github.com/18F/methods/issues/301
=> Fix flash of pull-down menus on page load

_methods/heuristic-evaluation.md, _pages/discover.md
Apologies if this PR is pointed at the wrong branch, but I didn't see a branch named `18f-pages-staging` to open against like the contributing docs recommended.
Changes: 
- File rename of heuristic-analysis to heuristic-evaluation
- Changed text "analysis" => "evaluation" for the method
Notes:
The reason for this change is to make the language clearer and more consistent around this method. If you search online for "Heuristic Analysis", one of the first results is [this Wikipedia article](https://en.wikipedia.org/wiki/Heuristic_analysis) that is about detecting viruses. Using the phrase "Evaluation" instead of "Analysis" should differentiate the two and possibly even help searchers find this page online. As for consistency, the link provided in the method itself points to an article that …
=> Changed Heuristic Analysis to Heuristic Evaluation

_methods/Design-hypotheses.md
Added suggested harm prompts from issue #420. Removed the link to the 18F Example since it has been archived. Added detail to "Additional resources" link.
Preview [here](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/methods/harm-prompts-design-hypothesis/decide/design-hypothesis/)
=> Add harm prompts to Design Hypothesis

_methods/content-audit.md
This PR replaces a broken link under "Additional resources" for content audit method.
> “Auditing Big Sites Doesn’t Have to Be Taxing.” Christine Anameier.
[PREVIEW](https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/brentryanjohnson-patch-2/decide/content-audit/)
=> Fixes broken link, content audit method

_data/categories.yml
Content audit has a dedicated markdown file, but it isn't generating in the list of methods on the homepage. It looks like the homepage loops through the `categories.yml` file to generate that list, so this PR adds "content audit" to the data file.
=> Adds content audit to _data file

_methods/multivariate-testing.md
The [multivariate testing method](https://methods.18f.gov/validate/multivariate-testing/) contains a broken link to "metrics analysis." It appears that method [was removed in an earlier release](https://methods.18f.gov/about/#210) and replaced with "design hypothesis." This PR replaces the broken link with the updated method.
=> Fixes broken link to metrics definition

_sass/touchpoints_overrides.scss
We deployed the Touchpoints feedback form, but realized that the inputs and textarea on the form displayed with too-small text. This PR fixes the sizing so that when you type in the form, the text displays at 1em (15px).
[Federalist preview](https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/445-touchpoints-fix-font-size/)
=> fix font size on feedback form input and textarea #445

_includes/footer.html, _includes/head.html, _sass/touchpoints_overrides.scss
Replace the touchpoints feedback modal with a link to the hosted version of the form because the modal doesn't get keyboard focus when launched #462
Can be previewed at: https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/462-touchpoints-temp-change/
=> Temp change Touchpoints feedback from modal to link to hosted form

_config.yml
The digital council is requesting all TTS sites to add "TTS" to the DAP script.
=> Add TTS and 18F to DAP script

_includes/footer.html
For DAP, we want to indicate Methods data is for TTS, as required.
To test:
- Use the Chrome extension Google Tag Assistant to make sure the tag is still sending data.
- After 48 hours, visit DAP Google Analytics to see if the data is coming through.
=> add dap subagency

index.html
- Adds category variable to link output to fix relative URLs in paths
[PREVIEW](https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/relative-paths-federalist/)
=> Adds category variable to path to fix Federalist previews

Gemfile.lock, _includes/footer.html
The methods.18f.gov site does not have the 18F email address as the contact. Instead it has a Touchpoints button labeled **Provide feedback** in the footer area.
To pass the scan, the label text should be one of the following:
- Contact Us
- Contact
- **Get in touch** 👈🏾 The `guide-admins` team chose this one
- Email Us
- Help Desk
**Before this change:** 
Changed the label text to Get in touch.
**After this change:** 
**Federalist Preview URL:** https://federalist-67816181-8ac2-428b-bc4e-be2d38d8f3ea.app.cloud.gov/preview/18f/methods/cannandev-change-touchpoints-label/
=> Cannandev change touchpoints label

_sass/sticky.scss
Closes #544
Essentially, the switch from mobile to desktop menu and the switch from mobile to desktop sticky banner were not aligning, because two different breakpoints were being used. This caused a slight window (from 950px to 64em) where css was conflicting and causing the mobile menu to rest behind the overlay. 
Using the standard USWDS breakpoint for both makes them sync up and removes the conflict. 
`@include at-media('desktop')` translates to a breakpoint of `min-width:64em` whereas `950px`, the old breakpoint, translates to `59.3em`.
I also removed the `min-width:100px` breakpoint since it was redundant. 
Tagging @MelissaBraxton as reporter of the original bug
Tagging @mgwalker for engineering review
=> Fix mobile button overlay by making desktop breakpoints consistent

.github/workflows/check_links.yml, .github/workflows/label_new_issues.yml, .github/workflows/sync-labels.yml
This pull requests adds some automations, like what has been previously added to the [UX guide](/18f/ux-guide):
- verify that there are no root-relative links in the source code
- verify that there are no invalid internal links in the build HTML
- synchronize labels with the UX guide repo nightly
- add the "new issue" label to newly-created issues, so maintenance teams can quickly know what has/has not been triaged
=> Add link testing, label syncing, and issue labeling

.github/workflows/sync-labels.yml
There was a recent PR that attempted to cause labels to sync as soon as they were created/updated/deleted. However, the action we use to sync labels does not ***push*** labels, it only pulls them. So when a label is created in repo A, repo A would pull from repo B. Repo B does not get a notification that repo A has a new label and repo B does not get synced.
This PR reverts back to the scheduled label sync for now.
=> Sync labels on a schedule

_methods/affinity-mapping.md, _methods/cognitive-walkthrough.md, _methods/content-audit.md, _methods/design-principles.md, _methods/heuristic-evaluation.md, _methods/journey-mapping.md, _methods/lean-coffee.md, _methods/mental-modeling.md, _methods/multivariate-testing.md, _methods/storyboarding.md, _methods/style-tiles.md, _methods/task-flow-analysis.md, _methods/visual-preference-testing.md, pages/participant-agreement-spanish.md, pages/rolling-issues-log.md, pages/usability-test-script.md, pages/user-interview-script.md
The following links were not updated because they are now 404s:
- Affinity mapping: [An explanation of affinity mapping](http://infodesign.com.au/usabilityresources/affinitydiagramming/) information and Design.
- Journey mapping: [Adaptive Path's Guide to Experience Mapping](http://adaptivepath.s3.amazonaws.com/apguide/download/Adaptive_Paths_Guide_to_Experience_Mapping.pdf) Adaptive Path (PDF)
- Interview checklist: there's a link to a methods page called "incentives," but there's not a page for that. So... that link is staying put too.
These two links only show up once each in the source, but because of how Methods are rendered, they appear multiple times in the built site.
Closes #579
=> Replace HTTP links with HTTPS links, where possible

_methods/privacy.md
This PR addresses a comment from a user pointing out that the privacy act was updated in 2020 and many of our links pointed to the previous version which was out of date.
=> Updated outdated privacy act link

_includes/footer.html
This PR updates the touchpoints CTA and the "contact us" approach in the footer. 
**Problems this solves:** 
- Current touchpoints CTA says "get in touch." We noticed that touchpoints responses are a mix of feedback and questions that expect a response. We hypothesize that "get in touch" is a bit vague and may mislead some users to think it's opening up a 2-way conversation, when the intention is really to focus in on feedback. 
**What we did:** 
- To help ensure that questions that require a response are routed correctly, we've revised the footer to point people to the 18F contact page if they want to get in touch. We've also revised the footer to make it more clear that the touchpoints intercept is designed to collect feedback on the Methods site specifically, and changed the CTA from …
=> Footer and touchpoints CTA updates

_methods/personas.md
no change to the url/wiki, but to the text of the link.
=> Changing federalist reference to cloud.gov

.github/workflows/sync_milestones.yml
Adds an automation to sync creation of milestones. When a milestone is created in this repo, the same milestone is also created in the [ux-guide](/18F/ux-guide) repo.
- Addresses 18F/ux-guide#374
@cannandev: Please review the GitHub Actions code. It is identical to 18F/ux-guide#382
@MelissaBraxton and/or @bpdesigns: Please review the behavior describe above to make sure it's right.
=> Add milestone syncing

_plugins/siteurl.rb
This PR just introduces building debug output. It can be reverted immediately after being merged.
none
=> Print cloud.gov environment variables to ensure they're what they're supposed to be
